const {expect}=require("chai");const {ethers}=require("hardhat");
describe("Liholiswano",function(){
 async function fixture(){const [owner,a,b,c]=await ethers.getSigners();const T=await ethers.getContractFactory("MockUSDT");const t=await T.deploy(owner.address,ethers.parseUnits("1000000",6));for(const u of [a,b,c])await t.mint(u.address,ethers.parseUnits("1000",6));const F=await ethers.getContractFactory("Liholiswano");const app=await F.deploy(owner.address,0);await app.setApprovedToken(t.target,true);return{owner,a,b,c,t,app};}
 async function group(f){const id=ethers.encodeBytes32String("LHS1"),con=ethers.parseUnits("100",6),col=ethers.parseUnits("50",6);await f.app.connect(f.a).createGroup(id,f.t.target,con,col,2000,3);for(const u of [f.a,f.b,f.c]){await f.t.connect(u).approve(f.app.target,ethers.MaxUint256);await f.app.connect(u).joinGroup(id);}return{id,con};}
 it("creates and locks",async()=>{const f=await fixture(),x=await group(f),g=await f.app.getGroup(x.id);expect(g[1]).eq(true);expect(g[14]).eq(3);expect(g[12]).gt(0);expect(g[13]).gt(0);});
 it("settles highest eligible bid",async()=>{const f=await fixture(),x=await group(f);for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,500);await f.app.connect(f.b).submitBid(x.id,1500);await f.app.connect(f.c).submitBid(x.id,1000);const before=await f.t.balanceOf(f.b.address);await f.app.settleRound(x.id);expect(await f.t.balanceOf(f.b.address)).eq(before+ethers.parseUnits("255",6));expect((await f.app.getMember(x.id,f.b.address)).totalWins).eq(1);});
 it("rejects duplicate contribution and bid",async()=>{const f=await fixture(),x=await group(f);await f.app.connect(f.a).contribute(x.id);await expect(f.app.connect(f.a).contribute(x.id)).to.be.revertedWithCustomError(f.app,"AlreadyContributed");await f.app.connect(f.a).submitBid(x.id,0);await expect(f.app.connect(f.a).submitBid(x.id,0)).to.be.revertedWithCustomError(f.app,"AlreadyBid");});
 it("records defaults only after the round deadline",async()=>{const f=await fixture(),x=await group(f);await expect(f.app.connect(f.a).markDefault(x.id,f.b.address)).to.be.revertedWithCustomError(f.app,"RoundNotDue");const before=await f.app.tokenBalance(x.id);await ethers.provider.send("evm_increaseTime",[24*60*60+1]);await ethers.provider.send("evm_mine",[]);await f.app.connect(f.a).markDefault(x.id,f.b.address);expect(await f.app.tokenBalance(x.id)).eq(before);expect((await f.app.getMember(x.id,f.b.address)).defaulted).eq(true);});
 it("starts a new rotation after all active members have won",async()=>{const f=await fixture(),x=await group(f);const bids=[[300,200,100],[100,300,200],[200,100,300]];for(let r=0;r<3;r++){for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);for(let i=0;i<3;i++){if(!(r>0&&i===0)&&!(r>1&&i===1))await f.app.connect([f.a,f.b,f.c][i]).submitBid(x.id,bids[r][i]);}await f.app.settleRound(x.id);}const g=await f.app.getGroup(x.id);expect(g[9]).eq(2);expect(g[8]).eq(4);});
 it("restricts token allowlisting to the owner",async()=>{const f=await fixture();await expect(f.app.connect(f.a).setApprovedToken(f.t.target,true)).to.be.revertedWithCustomError(f.app,"Unauthorized");});
 it("rejects unapproved tokens when creating a group",async()=>{const f=await fixture(),id=ethers.encodeBytes32String("BAD");await f.app.setApprovedToken(f.t.target,false);await expect(f.app.connect(f.a).createGroup(id,f.t.target,1,1,100,3)).to.be.revertedWithCustomError(f.app,"TokenNotApproved");});
 it("applies the configured protocol fee to the bid",async()=>{const f=await fixture(),x=await group(f);await f.app.setProtocolFeeBps(100);for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,0);await f.app.connect(f.b).submitBid(x.id,1000);await f.app.connect(f.c).submitBid(x.id,500);const treasuryBefore=await f.t.balanceOf(f.owner.address);await f.app.settleRound(x.id);expect(await f.t.balanceOf(f.owner.address)).eq(treasuryBefore+ethers.parseUnits("0.3",6));});
 it("does not settle before the deadline, then permissionlessly settles missing contributions as defaults",async()=>{const f=await fixture(),x=await group(f);await f.app.connect(f.a).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,100);await expect(f.app.settleRound(x.id)).to.be.revertedWithCustomError(f.app,"NotAllContributed");await ethers.provider.send("evm_increaseTime",[24*60*60+1]);await ethers.provider.send("evm_mine",[]);await f.app.connect(f.c).settleRound(x.id);expect((await f.app.getMember(x.id,f.b.address)).defaulted).eq(true);expect((await f.app.getMember(x.id,f.c.address)).defaulted).eq(true);expect((await f.app.getGroup(x.id))[8]).eq(2);});
 it("allows contract-controlled locking without an admin trigger and auto-locks when full",async()=>{const f=await fixture(),id=ethers.encodeBytes32String("LOCK");await f.app.connect(f.a).createGroup(id,f.t.target,1,1,100,3);for(const u of[f.a,f.b,f.c]){await f.t.connect(u).approve(f.app.target,ethers.MaxUint256);await f.app.connect(u).joinGroup(id);}expect((await f.app.getGroup(id))[1]).eq(true);const id2=ethers.encodeBytes32String("LOCK2");await f.app.connect(f.a).createGroup(id2,f.t.target,1,1,100,4);for(const u of[f.a,f.b,f.c]){await f.app.connect(u).joinGroup(id2);}await f.app.connect(f.b).lockGroup(id2);expect((await f.app.getGroup(id2))[1]).eq(true);await expect(f.app.connect(f.a).lockGroup(id2)).to.be.revertedWithCustomError(f.app,"GroupLocked");});
 it("rejects duplicate members and invalid fee or zero treasury",async()=>{const f=await fixture(),id=ethers.encodeBytes32String("DUP");await f.app.connect(f.a).createGroup(id,f.t.target,1,1,100,3);await f.t.connect(f.a).approve(f.app.target,ethers.MaxUint256);await f.app.connect(f.a).joinGroup(id);await expect(f.app.connect(f.a).joinGroup(id)).to.be.revertedWithCustomError(f.app,"AlreadyMember");await expect(f.app.setProtocolFeeBps(501)).to.be.revertedWithCustomError(f.app,"InvalidConfig");await expect(f.app.setTreasury(ethers.ZeroAddress)).to.be.revertedWithCustomError(f.app,"ZeroAddress");await expect(f.app.transferOwnership(ethers.ZeroAddress)).to.be.revertedWithCustomError(f.app,"ZeroAddress");await f.app.transferOwnership(f.a.address);expect(await f.app.pendingOwner()).eq(f.a.address);await expect(f.app.connect(f.b).acceptOwnership()).to.be.revertedWithCustomError(f.app,"Unauthorized");await f.app.connect(f.a).acceptOwnership();expect(await f.app.owner()).eq(f.a.address);});
 it("rejects late contributions and bids after the round deadline",async()=>{const f=await fixture(),x=await group(f);await ethers.provider.send("evm_increaseTime",[24*60*60+1]);await ethers.provider.send("evm_mine",[]);await expect(f.app.connect(f.a).contribute(x.id)).to.be.revertedWithCustomError(f.app,"RoundClosed");await expect(f.app.connect(f.a).submitBid(x.id,0)).to.be.revertedWithCustomError(f.app,"RoundClosed");});
 it("does not invent future shortfall for a member who has not won",async()=>{const f=await fixture(),x=await group(f);await ethers.provider.send("evm_increaseTime",[24*60*60+1]);await ethers.provider.send("evm_mine",[]);await f.app.markDefault(x.id,f.b.address);const g=await f.app.getGroup(x.id);expect(g[11]).eq(0);expect(g[10]).eq(g[5]);});
 it("defaults a member who contributed but never submitted a bid",async()=>{const f=await fixture(),x=await group(f);for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,100);await f.app.connect(f.b).submitBid(x.id,200);await ethers.provider.send("evm_increaseTime",[24*60*60+1]);await ethers.provider.send("evm_mine",[]);await f.app.connect(f.c).settleRound(x.id);expect((await f.app.getMember(x.id,f.c.address)).defaulted).eq(true);expect((await f.app.getGroup(x.id))[14]).eq(3);});
 it("keeps each group's escrow accounting isolated",async()=>{const f=await fixture(),x=await group(f);const id2=ethers.encodeBytes32String("G2");await f.app.connect(f.a).createGroup(id2,f.t.target,x.con,x.con,2000,3);for(const u of[f.a,f.b,f.c])await f.app.connect(u).joinGroup(id2);const g1=await f.app.getGroup(x.id),g2=await f.app.getGroup(id2);expect(g1[13]).eq(g1[5]*3n);expect(g2[13]).eq(g2[5]*3n);});
 it("pauses and unpauses all financial entrypoints",async()=>{const f=await fixture(),id=ethers.encodeBytes32String("PAUSE");await f.app.pause();expect(await f.app.paused()).eq(true);await expect(f.app.connect(f.a).createGroup(id,f.t.target,1,1,100,3)).to.be.revertedWithCustomError(f.app,"Paused");await f.app.unpause();await f.app.connect(f.a).createGroup(id,f.t.target,1,1,100,3);expect(await f.app.paused()).eq(false);await expect(f.app.connect(f.a).pause()).to.not.be.reverted;await expect(f.app.connect(f.a).unpause()).to.be.revertedWithCustomError(f.app,"Unauthorized");});
 it("rejects non-contract approved tokens",async()=>{const f=await fixture();await expect(f.app.setApprovedToken(f.a.address,true)).to.be.revertedWithCustomError(f.app,"InvalidToken");});
 it("blocks ERC20 callback reentrancy during settlement",async()=>{const [owner,a,b,c]=await ethers.getSigners();const T=await ethers.getContractFactory("ReentrantToken");const t=await T.deploy();for(const u of [a,b,c]){await t.mint(u.address,ethers.parseUnits("1000",6));}const F=await ethers.getContractFactory("Liholiswano");const app=await F.deploy(owner.address,0);await app.setApprovedToken(t.target,true);for(const u of[a,b,c])await t.connect(u).approve(app.target,ethers.MaxUint256);const id=ethers.encodeBytes32String("REENT");const con=ethers.parseUnits("100",6);await app.connect(a).createGroup(id,t.target,con,0,2000,3);for(const u of[a,b,c])await app.connect(u).joinGroup(id);for(const u of[a,b,c])await app.connect(u).contribute(id);await app.connect(a).submitBid(id,100);await app.connect(b).submitBid(id,200);await app.connect(c).submitBid(id,150);await t.configureAttack(app.target,app.interface.encodeFunctionData("settleRound",[id]),true);await expect(app.settleRound(id)).to.not.be.reverted;expect((await app.getMember(id,b.address)).totalWins).eq(1);});
 it("conserves token balance across isolated group escrow after settlement",async()=>{const f=await fixture(),x=await group(f);for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,500);await f.app.connect(f.b).submitBid(x.id,1500);await f.app.connect(f.c).submitBid(x.id,1000);await f.app.settleRound(x.id);const g=await f.app.getGroup(x.id);expect(await f.t.balanceOf(f.app.target)).eq(g[13]);expect(g[13]).eq(g[5]*3n);});
 it("rejects invalid group configuration",async()=>{const f=await fixture();const bad=async(id,con,col,maxBid,maxMembers)=>expect(f.app.connect(f.a).createGroup(ethers.encodeBytes32String(id),f.t.target,con,col,maxBid,maxMembers)).to.be.revertedWithCustomError(f.app,"InvalidConfig");await bad("C0",0,1,100,3);await bad("M2",1,1,100,2);await bad("M101",1,1,100,101);await bad("B5001",1,1,5001,3);});
});
