const {expect}=require("chai");const {ethers}=require("hardhat");
describe("Liholiswano",function(){
 async function fixture(){const [owner,a,b,c]=await ethers.getSigners();const T=await ethers.getContractFactory("MockUSDT");const t=await T.deploy(owner.address,ethers.parseUnits("1000000",6));for(const u of [a,b,c])await t.mint(u.address,ethers.parseUnits("1000",6));const F=await ethers.getContractFactory("Liholiswano");const app=await F.deploy(owner.address,0);await app.setApprovedToken(t.target,true);return{owner,a,b,c,t,app};}
 async function group(f){const id=ethers.encodeBytes32String("LHS1"),con=ethers.parseUnits("100",6),col=ethers.parseUnits("50",6);await f.app.connect(f.a).createGroup(id,f.t.target,con,col,2000,3);for(const u of [f.a,f.b,f.c]){await f.t.connect(u).approve(f.app.target,ethers.MaxUint256);await f.app.connect(u).joinGroup(id);}await f.app.connect(f.a).lockGroup(id);return{id,con};}
 it("creates and locks",async()=>{const f=await fixture(),x=await group(f),g=await f.app.getGroup(x.id);expect(g[1]).eq(true);expect(g[12]).eq(3);});
 it("settles highest eligible bid",async()=>{const f=await fixture(),x=await group(f);for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);await f.app.connect(f.a).submitBid(x.id,500);await f.app.connect(f.b).submitBid(x.id,1500);await f.app.connect(f.c).submitBid(x.id,1000);const before=await f.t.balanceOf(f.b.address);await f.app.settleRound(x.id);expect(await f.t.balanceOf(f.b.address)).eq(before+ethers.parseUnits("255",6));expect((await f.app.getMember(x.id,f.b.address)).totalWins).eq(1);});
 it("rejects duplicate contribution and bid",async()=>{const f=await fixture(),x=await group(f);await f.app.connect(f.a).contribute(x.id);await expect(f.app.connect(f.a).contribute(x.id)).to.be.revertedWithCustomError(f.app,"AlreadyContributed");await f.app.connect(f.a).submitBid(x.id,0);await expect(f.app.connect(f.a).submitBid(x.id,0)).to.be.revertedWithCustomError(f.app,"AlreadyBid");});
 it("records defaults without creating funds",async()=>{const f=await fixture(),x=await group(f);const before=await f.app.tokenBalance(x.id);await f.app.connect(f.a).markDefault(x.id,f.b.address);expect(await f.app.tokenBalance(x.id)).eq(before);expect((await f.app.getMember(x.id,f.b.address)).defaulted).eq(true);});
 it("starts a new rotation after all active members have won",async()=>{const f=await fixture(),x=await group(f);const bids=[[300,200,100],[100,300,200],[200,100,300]];for(let r=0;r<3;r++){for(const u of[f.a,f.b,f.c])await f.app.connect(u).contribute(x.id);for(let i=0;i<3;i++){if(!(r>0&&i===0)&&!(r>1&&i===1))await f.app.connect([f.a,f.b,f.c][i]).submitBid(x.id,bids[r][i]);}await f.app.settleRound(x.id);}const g=await f.app.getGroup(x.id);expect(g[9]).eq(2);expect(g[8]).eq(4);});
});