const {menu}=require("./whatsapp");
const {groupState,memberState,writableContract}=require("./blockchain");
const {assertAddress}=require("./wallet");
async function userByPhone(db,phone){const q=await db.query("select id,email,country,phone,kyc_status from users where phone=$1",[phone]);return q.rows[0]||null;}
async function handleCommand({phone,text,db}){
 const input=String(text||"").trim(), normalized=input.toLowerCase(), user=await userByPhone(db,phone);
 if(["hi","hello","menu","start"].includes(normalized)) return menu();
 if(!user)return "Your WhatsApp number is not linked to a Liholiswano account yet. Please complete account setup first.";
 if(normalized.startsWith("state ")){const id=input.slice(6).trim();try{const s=await groupState(process.env.BNB_CONTRACT_ADDRESS,id);return "ROSCA state\nRound: "+s.round+"\nMembers: "+s.memberCount+"\nContribution: "+s.contribution+"\nDeadline: "+new Date(s.roundDeadline*1000).toISOString();}catch(e){return "Unable to retrieve that ROSCA state.";}}
 if(normalized.startsWith("join ")){if(user.kyc_status!=="approved")return "KYC approval is required before joining a ROSCA.";const id=input.slice(5).trim();try{const s=await groupState(process.env.BNB_CONTRACT_ADDRESS,id);if(!s.exists)return "ROSCA group not found.";const wallet=await db.query("select address from wallets where user_id=$1 and is_primary=true",[user.id]);if(!wallet.rowCount)return "Please link a primary BNB wallet before joining.";assertAddress(wallet.rows[0].address);const existing=await db.query("select 1 from group_memberships gm join groups g on g.id=gm.group_id where gm.user_id=$1 and g.onchain_group_id=$2",[user.id,id]);if(existing.rowCount)return "You are already recorded as a member of this ROSCA.";return "ROSCA "+id+" is available. Managed-wallet transaction signing is not enabled yet, so no funds have been moved.";}catch(e){return "Unable to prepare the ROSCA join request.";}}
 if(normalized.startsWith("contribute ")){if(user.kyc_status!=="approved")return "KYC approval is required before contributing.";const parts=input.split(/\s+/);if(parts.length!==3)return "Use: CONTRIBUTE <group ID> <amount>";try{const s=await groupState(process.env.BNB_CONTRACT_ADDRESS,parts[1]);const wallet=await db.query("select address from wallets where user_id=$1 and is_primary=true",[user.id]);if(!wallet.rowCount)return "Please link a primary BNB wallet first.";const member=await memberState(process.env.BNB_CONTRACT_ADDRESS,parts[1],wallet.rows[0].address);if(!member.active)return "Your wallet is not an active member of this ROSCA.";return "Contribution request prepared for "+parts[2]+". Managed-wallet signing is not enabled yet, so no funds have moved.";}catch(e){return "Unable to prepare the contribution request.";}}
;