// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
contract Liholiswano {
 uint256 public constant BPS=10000; uint256 public constant MAX_BID_BPS=5000; uint256 public constant MIN_MEMBERS=3; uint256 public constant MAX_MEMBERS=100; uint256 public constant ROUND_DURATION=1 days;
 address public owner; address public pendingOwner; bool public paused; uint256 public protocolFeeBps; address public treasury; uint256 private reentrancyLock=1;
 mapping(address=>bool) public approvedToken; mapping(bytes32=>Group) private groups; bytes32[] private groupIds;
 struct Member {address account;bool active;bool defaulted;bool wonThisRotation;bool contributedThisRound;bool bidSubmitted;uint256 bidBps;uint32 totalWins;uint256 totalContributed;uint256 totalReceived;}
 struct Group {bool exists;bool locked;address admin;address token;uint256 contribution;uint256 collateral;uint256 maxMembers;uint256 maxBidBps;uint256 round;uint256 rotation;uint256 reserve;uint256 uncoveredShortfall;uint256 roundDeadline;uint256 escrowBalance;address[] memberAccounts;mapping(address=>Member) members;}
 error Unauthorized(); error GroupExists(); error GroupNotFound(); error InvalidConfig(); error InvalidToken(); error TokenNotApproved(); error GroupLocked(); error GroupFull(); error AlreadyMember(); error NotMember(); error NotActive(); error TooFewMembers(); error AlreadyContributed(); error AlreadyBid(); error BidTooHigh(); error NotLocked(); error NotAllContributed(); error NotAllBids(); error AlreadyWon(); error NothingToSettle(); error TransferFailed(); error TransferMismatch(); error ZeroAddress(); error NotDefaultable(); error RoundNotDue(); error RoundClosed(); error Reentrancy(); error Paused();
 event PausedStateChanged(bool paused,address indexed operator); event OwnershipTransferStarted(address indexed oldOwner,address indexed pendingOwner); event OwnershipTransferred(address indexed oldOwner,address indexed newOwner); event TreasuryChanged(address indexed oldTreasury,address indexed newTreasury); event ProtocolFeeChanged(uint256 oldFeeBps,uint256 newFeeBps); event TokenApprovalChanged(address indexed token,bool approved); event GroupCreated(bytes32 indexed groupId,address indexed admin,address indexed token); event MemberJoined(bytes32 indexed groupId,address indexed member); event GroupLockedEvent(bytes32 indexed groupId,uint256 round,uint256 deadline); event ContributionPaid(bytes32 indexed groupId,address indexed member,uint256 amount); event BidSubmitted(bytes32 indexed groupId,address indexed member,uint256 bidBps); event RoundSettled(bytes32 indexed groupId,uint256 round,address indexed winner,uint256 bidAmount,uint256 payout); event MemberDefaulted(bytes32 indexed groupId,address indexed member,uint256 collateral,uint256 uncovered);
 constructor(address initialTreasury,uint256 initialFeeBps){if(initialTreasury==address(0)||initialFeeBps>500)revert InvalidConfig();owner=msg.sender;treasury=initialTreasury;protocolFeeBps=initialFeeBps;emit OwnershipTransferred(address(0),msg.sender);}
 modifier onlyOwner(){if(msg.sender!=owner)revert Unauthorized();_;}
 modifier whenNotPaused(){if(paused)revert Paused();_;} modifier nonReentrant(){if(reentrancyLock!=1)revert Reentrancy();reentrancyLock=2;_;reentrancyLock=1;}
 function pause() external onlyOwner{if(!paused){paused=true;emit PausedStateChanged(true,msg.sender);}} function unpause() external onlyOwner{if(paused){paused=false;emit PausedStateChanged(false,msg.sender);}} function transferOwnership(address n) external onlyOwner{if(n==address(0))revert ZeroAddress();pendingOwner=n;emit OwnershipTransferStarted(owner,n);}
 function acceptOwnership() external{if(msg.sender!=pendingOwner)revert Unauthorized();address oldOwner=owner;owner=msg.sender;pendingOwner=address(0);emit OwnershipTransferred(oldOwner,msg.sender);}
 function setTreasury(address n) external onlyOwner{if(n==address(0))revert ZeroAddress();emit TreasuryChanged(treasury,n);treasury=n;}
 function setProtocolFeeBps(uint256 n) external onlyOwner{if(n>500)revert InvalidConfig();emit ProtocolFeeChanged(protocolFeeBps,n);protocolFeeBps=n;}
 function setApprovedToken(address t,bool a) external onlyOwner{if(t==address(0)||t.code.length==0)revert InvalidToken();approvedToken[t]=a;emit TokenApprovalChanged(t,a);}
 function createGroup(bytes32 id,address token,uint256 contribution,uint256 collateral,uint256 maxBidBps,uint256 maxMembers) external whenNotPaused{if(groups[id].exists)revert GroupExists();if(!approvedToken[token])revert TokenNotApproved();if(token.code.length==0)revert InvalidToken();if(contribution==0||maxMembers<MIN_MEMBERS||maxMembers>MAX_MEMBERS||maxBidBps>MAX_BID_BPS)revert InvalidConfig();Group storage g=groups[id];g.exists=true;g.admin=msg.sender;g.token=token;g.contribution=contribution;g.collateral=collateral;g.maxMembers=maxMembers;g.maxBidBps=maxBidBps;groupIds.push(id);emit GroupCreated(id,msg.sender,token);}
 function joinGroup(bytes32 id) external whenNotPaused nonReentrant{Group storage g=_group(id);if(g.locked)revert GroupLocked();if(g.memberAccounts.length>=g.maxMembers)revert GroupFull();if(g.members[msg.sender].account!=address(0))revert AlreadyMember();if(g.collateral>0){_transferFromExact(g.token,msg.sender,address(this),g.collateral);g.escrowBalance+=g.collateral;}g.memberAccounts.push(msg.sender);g.members[msg.sender]=Member(msg.sender,true,false,false,false,false,0,0,0,0);emit MemberJoined(id,msg.sender);if(g.memberAccounts.length==g.maxMembers){_lockGroup(g,id);}}
 function lockGroup(bytes32 id) external whenNotPaused{Group storage g=_group(id);_lockGroup(g,id);}
 function _lockGroup(Group storage g,bytes32 id) internal{if(g.locked)revert GroupLocked();if(g.memberAccounts.length<MIN_MEMBERS)revert TooFewMembers();g.locked=true;g.round=1;g.rotation=1;g.roundDeadline=block.timestamp+ROUND_DURATION;emit GroupLockedEvent(id,1,g.roundDeadline);}
 function contribute(bytes32 id) external whenNotPaused nonReentrant{Group storage g=_group(id);if(!g.locked)revert NotLocked();if(block.timestamp>=g.roundDeadline)revert RoundClosed();Member storage m=_member(g,msg.sender);if(!m.active)revert NotActive();if(m.contributedThisRound)revert AlreadyContributed();_transferFromExact(g.token,msg.sender,address(this),g.contribution);g.escrowBalance+=g.contribution;m.contributedThisRound=true;m.totalContributed+=g.contribution;emit ContributionPaid(id,msg.sender,g.contribution);}
 function submitBid(bytes32 id,uint256 bidBps) external whenNotPaused{Group storage g=_group(id);if(!g.locked)revert NotLocked();if(block.timestamp>=g.roundDeadline)revert RoundClosed();if(bidBps>g.maxBidBps)revert BidTooHigh();Member storage m=_member(g,msg.sender);if(!m.active)revert NotActive();if(m.wonThisRotation)revert AlreadyWon();if(m.bidSubmitted)revert AlreadyBid();m.bidSubmitted=true;m.bidBps=bidBps;emit BidSubmitted(id,msg.sender,bidBps);}
 function settleRound(bytes32 id) external whenNotPaused nonReentrant{Group storage g=_group(id);if(!g.locked)revert NotLocked();bool due=block.timestamp>=g.roundDeadline;if(!due){for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;if(!m.contributedThisRound)revert NotAllContributed();if(!m.wonThisRotation&&!m.bidSubmitted)revert NotAllBids();}}else{for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;if(!m.contributedThisRound||(!m.wonThisRotation&&!m.bidSubmitted))_defaultMember(g,id,m);}}uint256 active;uint256 eligible;uint256 winnerIndex;uint256 winnerBid;bool winnerFound;for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;active++;if(!m.wonThisRotation){eligible++;if(!winnerFound||m.bidBps>winnerBid){winnerFound=true;winnerBid=m.bidBps;winnerIndex=i;}}}if(active==0||eligible==0||!winnerFound)revert NothingToSettle();uint256 pot=active*g.contribution;if(g.escrowBalance<pot)revert TransferFailed();uint256 bidAmount=pot*winnerBid/BPS;uint256 payout=pot-bidAmount;uint256 fee=bidAmount*protocolFeeBps/BPS;uint256 distributable=bidAmount-fee;uint256 others=active-1;uint256 share=others==0?0:distributable/others;uint256 remainder=distributable-share*others;address winner=g.memberAccounts[winnerIndex];if(payout>0)_transferExact(g.token,winner,payout);if(fee>0)_transferExact(g.token,treasury,fee);for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;if(i==winnerIndex){m.wonThisRotation=true;m.totalWins++;m.totalReceived+=payout+remainder;if(remainder>0)_transferExact(g.token,m.account,remainder);}else if(share>0){_transferExact(g.token,m.account,share);m.totalReceived+=share;}m.contributedThisRound=false;m.bidSubmitted=false;m.bidBps=0;}g.escrowBalance-=pot;emit RoundSettled(id,g.round,winner,bidAmount,payout+remainder);g.round++;g.roundDeadline=block.timestamp+ROUND_DURATION;if(_eligibleCount(g)==0){g.rotation++;for(uint256 i;i<g.memberAccounts.length;i++){if(g.members[g.memberAccounts[i]].active)g.members[g.memberAccounts[i]].wonThisRotation=false;}}}
 function markDefault(bytes32 id,address member) external whenNotPaused nonReentrant{Group storage g=_group(id);if(block.timestamp<g.roundDeadline)revert RoundNotDue();Member storage m=_member(g,member);if(!m.active||m.defaulted)revert NotDefaultable();if(m.contributedThisRound&&(m.bidSubmitted||m.wonThisRotation))revert NotDefaultable();_defaultMember(g,id,m);}
 function getGroup(bytes32 id) external view returns(bool,bool,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256){Group storage g=_group(id);return(g.exists,g.locked,g.admin,g.token,g.contribution,g.collateral,g.maxMembers,g.maxBidBps,g.round,g.rotation,g.reserve,g.uncoveredShortfall,g.roundDeadline,g.escrowBalance,g.memberAccounts.length);}
 function getMembers(bytes32 id) external view returns(Member[] memory){Group storage g=_group(id);Member[] memory out=new Member[](g.memberAccounts.length);for(uint256 i;i<g.memberAccounts.length;i++)out[i]=g.members[g.memberAccounts[i]];return out;}
 function getMember(bytes32 id,address a) external view returns(Member memory){return _member(_group(id),a);}
 function getGroupIds() external view returns(bytes32[] memory){return groupIds;}
 function tokenBalance(bytes32 id) external view returns(uint256){return IERC20Minimal(_group(id).token).balanceOf(address(this));}
 function _eligibleCount(Group storage g) internal view returns(uint256 n){for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(m.active&&!m.wonThisRotation)n++;}}
 function _defaultMember(Group storage g,bytes32 id,Member storage m) internal{if(!m.active||m.defaulted)revert NotDefaultable();if(m.contributedThisRound&&(m.bidSubmitted||m.wonThisRotation))revert NotDefaultable();uint256 uncovered;if(m.wonThisRotation){uint256 remaining;for(uint256 i;i<g.memberAccounts.length;i++){Member storage other=g.members[g.memberAccounts[i]];if(other.active&&!other.wonThisRotation&&other.account!=m.account)remaining++;}uint256 owed=remaining*g.contribution;uncovered=owed>g.collateral?owed-g.collateral:0;}m.active=false;m.defaulted=true;g.reserve+=g.collateral+(m.contributedThisRound?g.contribution:0);g.uncoveredShortfall+=uncovered;emit MemberDefaulted(id,m.account,g.collateral,uncovered);}
 function _group(bytes32 id) internal view returns(Group storage g){g=groups[id];if(!g.exists)revert GroupNotFound();}
 function _member(Group storage g,address a) internal view returns(Member storage m){m=g.members[a];if(m.account==address(0))revert NotMember();}
 function _transferFromExact(address t,address f,address to,uint256 a) internal{uint256 beforeBalance=IERC20Minimal(t).balanceOf(to);(bool ok,bytes memory d)=t.call(abi.encodeWithSelector(IERC20Minimal.transferFrom.selector,f,to,a));if(!ok||(d.length>0&&!abi.decode(d,(bool))))revert TransferFailed();uint256 afterBalance=IERC20Minimal(t).balanceOf(to);if(afterBalance<beforeBalance||afterBalance-beforeBalance!=a)revert TransferMismatch();}
 function _transferExact(address t,address to,uint256 a) internal{uint256 beforeBalance=IERC20Minimal(t).balanceOf(to);(bool ok,bytes memory d)=t.call(abi.encodeWithSelector(IERC20Minimal.transfer.selector,to,a));if(!ok||(d.length>0&&!abi.decode(d,(bool))))revert TransferFailed();uint256 afterBalance=IERC20Minimal(t).balanceOf(to);if(afterBalance<beforeBalance||afterBalance-beforeBalance!=a)revert TransferMismatch();}
}
interface IERC20Minimal{function transfer(address to,uint256 amount) external returns(bool);function transferFrom(address from,address to,uint256 amount) external returns(bool);function balanceOf(address account) external view returns(uint256);}