// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
contract Liholiswano {
 uint256 public constant BPS=10000; uint256 public constant MAX_BID_BPS=5000; uint256 public constant MIN_MEMBERS=3; uint256 public constant ROUND_DURATION=1 days;
 address public owner; uint256 public protocolFeeBps; address public treasury;
 mapping(address=>bool) public approvedToken; mapping(bytes32=>Group) private groups; bytes32[] private groupIds;
 struct Member {address account;bool active;bool defaulted;bool wonThisRotation;bool contributedThisRound;int256 bidBps;uint32 totalWins;uint256 totalContributed;uint256 totalReceived;}
 struct Group {bool exists;bool locked;address admin;address token;uint256 contribution;uint256 collateral;uint256 maxMembers;uint256 maxBidBps;uint256 round;uint256 rotation;uint256 reserve;uint256 uncoveredShortfall;uint256 roundDeadline;address[] memberAccounts;mapping(address=>Member) members;}
 error Unauthorized(); error GroupExists(); error GroupNotFound(); error InvalidConfig(); error TokenNotApproved(); error GroupLocked(); error GroupFull(); error AlreadyMember(); error NotMember(); error NotActive(); error TooFewMembers(); error AlreadyContributed(); error AlreadyBid(); error BidTooHigh(); error NotLocked(); error NotAllContributed(); error NotAllBids(); error AlreadyWon(); error NothingToSettle(); error TransferFailed(); error ZeroAddress(); error NotDefaultable(); error RoundNotDue();
 event OwnershipTransferred(address indexed oldOwner,address indexed newOwner); event TokenApprovalChanged(address indexed token,bool approved); event GroupCreated(bytes32 indexed groupId,address indexed admin,address indexed token); event MemberJoined(bytes32 indexed groupId,address indexed member); event GroupLockedEvent(bytes32 indexed groupId,uint256 round); event ContributionPaid(bytes32 indexed groupId,address indexed member,uint256 amount); event BidSubmitted(bytes32 indexed groupId,address indexed member,uint256 bidBps); event RoundSettled(bytes32 indexed groupId,uint256 round,address indexed winner,uint256 bidAmount,uint256 payout); event MemberDefaulted(bytes32 indexed groupId,address indexed member,uint256 collateral,uint256 uncovered);
 constructor(address initialTreasury,uint256 initialFeeBps){if(initialTreasury==address(0)||initialFeeBps>500)revert InvalidConfig();owner=msg.sender;treasury=initialTreasury;protocolFeeBps=initialFeeBps;emit OwnershipTransferred(address(0),msg.sender);}
 modifier onlyOwner(){if(msg.sender!=owner)revert Unauthorized();_;}
 modifier onlyGroupAdmin(bytes32 id){if(!groups[id].exists)revert GroupNotFound();if(groups[id].admin!=msg.sender)revert Unauthorized();_;}
 function transferOwnership(address n) external onlyOwner{if(n==address(0))revert ZeroAddress();emit OwnershipTransferred(owner,n);owner=n;}
 function setTreasury(address n) external onlyOwner{if(n==address(0))revert ZeroAddress();treasury=n;}
 function setProtocolFeeBps(uint256 n) external onlyOwner{if(n>500)revert InvalidConfig();protocolFeeBps=n;}
 function setApprovedToken(address t,bool a) external onlyOwner{if(t==address(0))revert ZeroAddress();approvedToken[t]=a;emit TokenApprovalChanged(t,a);}
 function createGroup(bytes32 id,address token,uint256 contribution,uint256 collateral,uint256 maxBidBps,uint256 maxMembers) external{if(groups[id].exists)revert GroupExists();if(!approvedToken[token])revert TokenNotApproved();if(contribution==0||maxMembers<MIN_MEMBERS||maxMembers>100||maxBidBps>MAX_BID_BPS)revert InvalidConfig();Group storage g=groups[id];g.exists=true;g.admin=msg.sender;g.token=token;g.contribution=contribution;g.collateral=collateral;g.maxMembers=maxMembers;g.maxBidBps=maxBidBps;groupIds.push(id);emit GroupCreated(id,msg.sender,token);}
 function joinGroup(bytes32 id) external{Group storage g=_group(id);if(g.locked)revert GroupLocked();if(g.memberAccounts.length>=g.maxMembers)revert GroupFull();if(g.members[msg.sender].account!=address(0))revert AlreadyMember();if(g.collateral>0)_transferFrom(g.token,msg.sender,address(this),g.collateral);g.memberAccounts.push(msg.sender);g.members[msg.sender]=Member(msg.sender,true,false,false,false,-1,0,0,0);emit MemberJoined(id,msg.sender);if(g.memberAccounts.length==g.maxMembers){_lockGroup(g,id);}}
 function lockGroup(bytes32 id) external{Group storage g=_group(id);_lockGroup(g,id);}
 function _lockGroup(Group storage g,bytes32 id) internal{if(g.locked)revert GroupLocked();if(g.memberAccounts.length<MIN_MEMBERS)revert TooFewMembers();g.locked=true;g.round=1;g.rotation=1;g.roundDeadline=block.timestamp+ROUND_DURATION;emit GroupLockedEvent(id,1);}
 function contribute(bytes32 id) external{Group storage g=_group(id);if(!g.locked)revert NotLocked();Member storage m=_member(g,msg.sender);if(!m.active)revert NotActive();if(m.contributedThisRound)revert AlreadyContributed();_transferFrom(g.token,msg.sender,address(this),g.contribution);m.contributedThisRound=true;m.totalContributed+=g.contribution;emit ContributionPaid(id,msg.sender,g.contribution);}
 function submitBid(bytes32 id,uint256 bidBps) external{Group storage g=_group(id);if(!g.locked)revert NotLocked();if(bidBps>g.maxBidBps)revert BidTooHigh();Member storage m=_member(g,msg.sender);if(!m.active)revert NotActive();if(m.wonThisRotation)revert AlreadyWon();if(m.bidBps>=0)revert AlreadyBid();m.bidBps=int256(bidBps);emit BidSubmitted(id,msg.sender,bidBps);}
 function settleRound(bytes32 id) external{Group storage g=_group(id);if(!g.locked)revert NotLocked();bool due=block.timestamp>=g.roundDeadline;uint256 active;uint256 eligible;uint256 winnerIndex;uint256 winnerBid;for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;if(!m.contributedThisRound){if(!due)revert NotAllContributed();_markDefault(g,id,m);continue;}active++;if(!m.wonThisRotation){if(m.bidBps<0&&!due)revert NotAllBids();eligible++;if(uint256(m.bidBps)>winnerBid){winnerBid=uint256(m.bidBps);winnerIndex=i;}}}if(active==0||eligible==0)revert NothingToSettle();uint256 pot=active*g.contribution;uint256 bidAmount=pot*winnerBid/BPS;uint256 payout=pot-bidAmount;uint256 fee=bidAmount*protocolFeeBps/BPS;uint256 distributable=bidAmount-fee;uint256 others=active-1;uint256 share=others==0?0:distributable/others;uint256 remainder=distributable-share*others;address winner=g.memberAccounts[winnerIndex];if(payout>0)_transfer(g.token,winner,payout);if(fee>0)_transfer(g.token,treasury,fee);for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(!m.active)continue;if(i==winnerIndex){m.wonThisRotation=true;m.totalWins++;m.totalReceived+=payout;}else if(share>0){_transfer(g.token,m.account,share);m.totalReceived+=share;}m.contributedThisRound=false;m.bidBps=-1;}g.reserve+=remainder;emit RoundSettled(id,g.round,winner,bidAmount,payout);g.round++;g.roundDeadline=block.timestamp+ROUND_DURATION;if(_eligibleCount(g)==0){g.rotation++;for(uint256 i;i<g.memberAccounts.length;i++){if(g.members[g.memberAccounts[i]].active)g.members[g.memberAccounts[i]].wonThisRotation=false;}}}
 function markDefault(bytes32 id,address member) external{Group storage g=_group(id);if(block.timestamp<g.roundDeadline)revert RoundNotDue();Member storage m=_member(g,member);if(!m.active||m.defaulted)revert NotDefaultable();if(m.contributedThisRound)revert NotDefaultable();uint256 uncovered;if(m.wonThisRotation){uint256 remaining;for(uint256 i;i<g.memberAccounts.length;i++){Member storage o=g.members[g.memberAccounts[i]];if(o.active&&!o.wonThisRotation&&o.account!=member)remaining++;}uint256 owed=remaining*g.contribution;uncovered=owed>g.collateral?owed-g.collateral:0;}m.active=false;m.defaulted=true;g.reserve+=g.collateral;g.uncoveredShortfall+=uncovered;emit MemberDefaulted(id,member,g.collateral,uncovered);} function _markDefault(Group storage g,bytes32 id,Member storage m) internal{if(!m.active||m.defaulted||m.contributedThisRound)return;uint256 uncovered;if(m.wonThisRotation){uint256 remaining;for(uint256 i;i<g.memberAccounts.length;i++){Member storage o=g.members[g.memberAccounts[i]];if(o.active&&!o.wonThisRotation&&o.account!=m.account)remaining++;}uint256 owed=remaining*g.contribution;uncovered=owed>g.collateral?owed-g.collateral:0;}m.active=false;m.defaulted=true;g.reserve+=g.collateral;g.uncoveredShortfall+=uncovered;emit MemberDefaulted(id,m.account,g.collateral,uncovered);}
 function getGroup(bytes32 id) external view returns(bool,bool,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256){Group storage g=_group(id);return(g.exists,g.locked,g.admin,g.token,g.contribution,g.collateral,g.maxMembers,g.maxBidBps,g.round,g.rotation,g.reserve,g.uncoveredShortfall,g.roundDeadline,g.memberAccounts.length);}
 function getMembers(bytes32 id) external view returns(Member[] memory){Group storage g=_group(id);Member[] memory out=new Member[](g.memberAccounts.length);for(uint256 i;i<g.memberAccounts.length;i++)out[i]=g.members[g.memberAccounts[i]];return out;}
 function getMember(bytes32 id,address a) external view returns(Member memory){return _member(_group(id),a);}
 function getGroupIds() external view returns(bytes32[] memory){return groupIds;}
 function tokenBalance(bytes32 id) external view returns(uint256){return IERC20Minimal(_group(id).token).balanceOf(address(this));}
 function _eligibleCount(Group storage g) internal view returns(uint256 n){for(uint256 i;i<g.memberAccounts.length;i++){Member storage m=g.members[g.memberAccounts[i]];if(m.active&&!m.wonThisRotation)n++;}}
 function _group(bytes32 id) internal view returns(Group storage g){g=groups[id];if(!g.exists)revert GroupNotFound();}
 function _member(Group storage g,address a) internal view returns(Member storage m){m=g.members[a];if(m.account==address(0))revert NotMember();}
 function _transferFrom(address t,address f,address to,uint256 a) internal{(bool ok,bytes memory d)=t.call(abi.encodeWithSelector(IERC20Minimal.transferFrom.selector,f,to,a));if(!ok||(d.length>0&&!abi.decode(d,(bool))))revert TransferFailed();}
 function _transfer(address t,address to,uint256 a) internal{(bool ok,bytes memory d)=t.call(abi.encodeWithSelector(IERC20Minimal.transfer.selector,to,a));if(!ok||(d.length>0&&!abi.decode(d,(bool))))revert TransferFailed();}
}
interface IERC20Minimal{function transfer(address to,uint256 amount) external returns(bool);function transferFrom(address from,address to,uint256 amount) external returns(bool);function balanceOf(address account) external view returns(uint256);}