name: Contract tests

on:
  push:
    paths:
      - "contract/**"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Work around a known ethnum/Rust incompatibility
        working-directory: contract
        run: cargo update -p ethnum --precise 1.5.3

      - name: Run the contract's unit tests
        working-directory: contract
        run: cargo test
